import type mysql from 'mysql2/promise'

const jobs = [
  // --- Account Executive (10) ---
  {
    id: 'ae-salesforce-sf',
    title: 'Enterprise Account Executive',
    company_name: 'Salesforce',
    company_website: 'https://salesforce.com',
    location: 'San Francisco, CA',
    work_type: 'Hybrid',
    seniority: 'Senior',
    sector: 'SaaS',
    description: 'Own new business across Fortune 500 accounts in the West region. Full sales cycle from prospecting to close on six-figure deals. 5+ years enterprise SaaS sales required.',
    base_salary: '$130k - $155k',
    ote: '$260k - $310k',
    commission_structure: 'Uncapped commission with 2x accelerators above 100% quota.',
    currency: 'USD',
    application_url: 'https://salesforce.com/careers',
    contact_email: 'recruiting@salesforce.com',
    featured: 1,
  },
  {
    id: 'ae-hubspot-remote',
    title: 'Mid-Market Account Executive',
    company_name: 'HubSpot',
    company_website: 'https://hubspot.com',
    location: 'Remote (US)',
    work_type: 'Remote',
    seniority: 'Mid-Level',
    sector: 'SaaS',
    description: 'Close mid-market deals across North America for HubSpot\'s CRM suite. Work closely with SDRs to convert inbound pipeline and build net-new outbound book.',
    base_salary: '$80k - $100k',
    ote: '$160k - $200k',
    commission_structure: 'Monthly quota, quarterly accelerators at 110% and 125%.',
    currency: 'USD',
    application_url: 'https://hubspot.com/careers',
    contact_email: 'talent@hubspot.com',
    featured: 0,
  },
  {
    id: 'ae-workday-nyc',
    title: 'Strategic Account Executive',
    company_name: 'Workday',
    company_website: 'https://workday.com',
    location: 'New York, NY',
    work_type: 'Hybrid',
    seniority: 'Senior',
    sector: 'SaaS',
    description: 'Drive net-new enterprise logo acquisition for Workday\'s HCM and Finance platform across the Northeast. Own complex 6-18 month sales cycles with C-suite stakeholders.',
    base_salary: '$140k - $170k',
    ote: '$280k - $340k',
    commission_structure: 'Tiered commission. SPIFs on multi-year deals.',
    currency: 'USD',
    application_url: 'https://workday.com/careers',
    contact_email: 'careers@workday.com',
    featured: 1,
  },
  {
    id: 'ae-servicenow-chicago',
    title: 'Account Executive, Commercial',
    company_name: 'ServiceNow',
    company_website: 'https://servicenow.com',
    location: 'Chicago, IL',
    work_type: 'Hybrid',
    seniority: 'Mid-Level',
    sector: 'SaaS',
    description: 'Prospect and close commercial accounts in the Midwest for ServiceNow\'s ITSM and workflow automation platform. Build and manage a pipeline of 80+ opportunities per quarter.',
    base_salary: '$90k - $115k',
    ote: '$180k - $230k',
    commission_structure: 'Uncapped. 1.5x multiplier from 100-125%, 2x above 125%.',
    currency: 'USD',
    application_url: 'https://servicenow.com/careers',
    contact_email: 'hiring@servicenow.com',
    featured: 0,
  },
  {
    id: 'ae-zendesk-london',
    title: 'Account Executive, EMEA',
    company_name: 'Zendesk',
    company_website: 'https://zendesk.com',
    location: 'London, UK',
    work_type: 'Hybrid',
    seniority: 'Senior',
    sector: 'SaaS',
    description: 'Own new business and expansion revenue across UK and Benelux for Zendesk\'s CX platform. Target VP and C-level buyers at scale-ups and enterprise accounts.',
    base_salary: '£85k - £105k',
    ote: '£170k - £210k',
    commission_structure: 'Quarterly commission with annual accelerators. No cap.',
    currency: 'GBP',
    application_url: 'https://zendesk.com/jobs',
    contact_email: 'emea-recruiting@zendesk.com',
    featured: 0,
  },
  {
    id: 'ae-gong-austin',
    title: 'Account Executive, Enterprise',
    company_name: 'Gong',
    company_website: 'https://gong.io',
    location: 'Austin, TX',
    work_type: 'Remote',
    seniority: 'Senior',
    sector: 'SaaS',
    description: 'Sell Gong\'s revenue intelligence platform to VP Sales and RevOps at enterprise accounts. Average deal size $80k ARR. Own full cycle from outbound to close.',
    base_salary: '$120k - $145k',
    ote: '$240k - $290k',
    commission_structure: 'Uncapped commission. President\'s club qualification at 120%+.',
    currency: 'USD',
    application_url: 'https://gong.io/careers',
    contact_email: 'hiring@gong.io',
    featured: 1,
  },
  {
    id: 'ae-datadog-sydney',
    title: 'Account Executive, ANZ',
    company_name: 'Datadog',
    company_website: 'https://datadoghq.com',
    location: 'Sydney, Australia',
    work_type: 'Hybrid',
    seniority: 'Senior',
    sector: 'SaaS',
    description: 'Drive new business across ANZ for Datadog\'s observability and security platform. Target DevOps leaders and CISOs at mid-market and enterprise accounts.',
    base_salary: 'A$130k - A$155k',
    ote: 'A$260k - A$310k',
    commission_structure: 'Uncapped. Quarterly accelerators from 100%.',
    currency: 'AUD',
    application_url: 'https://datadoghq.com/careers',
    contact_email: 'apac-hiring@datadoghq.com',
    featured: 0,
  },
  {
    id: 'ae-stripe-nyc',
    title: 'Account Executive, Fintech',
    company_name: 'Stripe',
    company_website: 'https://stripe.com',
    location: 'New York, NY',
    work_type: 'Hybrid',
    seniority: 'Senior',
    sector: 'FinTech',
    description: 'Own fintech and payments company relationships for Stripe\'s enterprise suite. Work with technical founders, CFOs, and CTOs on complex payments infrastructure deals.',
    base_salary: '$130k - $160k',
    ote: '$260k - $320k',
    commission_structure: 'Commission on TPV growth plus net new ARR.',
    currency: 'USD',
    application_url: 'https://stripe.com/jobs',
    contact_email: 'ae-recruiting@stripe.com',
    featured: 1,
  },
  {
    id: 'ae-okta-remote',
    title: 'Account Executive, SMB',
    company_name: 'Okta',
    company_website: 'https://okta.com',
    location: 'Remote (US)',
    work_type: 'Remote',
    seniority: 'Entry Level',
    sector: 'Cybersecurity',
    description: 'High-velocity role closing 10-20 deals per month in the SMB segment. Ideal for a former SDR ready to own a full sales cycle. Okta provides best-in-class onboarding and ramp support.',
    base_salary: '$65k - $80k',
    ote: '$115k - $145k',
    commission_structure: 'Monthly quota. Uncapped with quarterly kickers.',
    currency: 'USD',
    application_url: 'https://okta.com/company/careers',
    contact_email: 'smb-sales@okta.com',
    featured: 0,
  },
  {
    id: 'ae-intercom-dublin',
    title: 'Account Executive, Growth',
    company_name: 'Intercom',
    company_website: 'https://intercom.com',
    location: 'Dublin, Ireland',
    work_type: 'Hybrid',
    seniority: 'Mid-Level',
    sector: 'SaaS',
    description: 'Close growth segment deals for Intercom\'s AI-first customer service platform. Work with CX and product leaders at SaaS companies scaling from 50 to 500 people.',
    base_salary: '€75k - €95k',
    ote: '€150k - €190k',
    commission_structure: 'Monthly commissions, no cap. Annual accelerator at 120%+.',
    currency: 'EUR',
    application_url: 'https://intercom.com/careers',
    contact_email: 'sales-hiring@intercom.com',
    featured: 0,
  },

  // --- SDR / BDR (10) ---
  {
    id: 'sdr-hubspot-dublin',
    title: 'Sales Development Representative',
    company_name: 'HubSpot',
    company_website: 'https://hubspot.com',
    location: 'Dublin, Ireland',
    work_type: 'Hybrid',
    seniority: 'Entry Level',
    sector: 'SaaS',
    description: 'Generate qualified pipeline for the EMEA AE team through outbound prospecting and inbound lead qualification. Clear promotion path to AE within 12-18 months.',
    base_salary: '€45k - €55k',
    ote: '€65k - €80k',
    commission_structure: 'Per qualified meeting booked plus quarterly pipeline attainment bonus.',
    currency: 'EUR',
    application_url: 'https://hubspot.com/careers',
    contact_email: 'sdr-recruiting@hubspot.com',
    featured: 0,
  },
  {
    id: 'bdr-salesforce-london',
    title: 'Business Development Representative',
    company_name: 'Salesforce',
    company_website: 'https://salesforce.com',
    location: 'London, UK',
    work_type: 'Hybrid',
    seniority: 'Entry Level',
    sector: 'SaaS',
    description: 'Drive outbound prospecting across UK enterprise accounts for Salesforce\'s Sales Cloud. Partner with Senior AEs on deal strategy and account penetration.',
    base_salary: '£38k - £48k',
    ote: '£58k - £75k',
    commission_structure: 'Monthly variable on SQOs and pipeline created.',
    currency: 'GBP',
    application_url: 'https://salesforce.com/careers',
    contact_email: 'uk-bdr@salesforce.com',
    featured: 0,
  },
  {
    id: 'sdr-snowflake-remote',
    title: 'Sales Development Representative',
    company_name: 'Snowflake',
    company_website: 'https://snowflake.com',
    location: 'Remote (US)',
    work_type: 'Remote',
    seniority: 'Entry Level',
    sector: 'SaaS',
    description: 'Source pipeline for Snowflake\'s data cloud platform through targeted outbound to engineering and data leaders at mid-market tech companies. Stock options from day one.',
    base_salary: '$55k - $70k',
    ote: '$85k - $105k',
    commission_structure: 'Quota on SQOs created. Uncapped with team performance bonus.',
    currency: 'USD',
    application_url: 'https://snowflake.com/careers',
    contact_email: 'sdr@snowflake.com',
    featured: 0,
  },
  {
    id: 'bdr-zendesk-melbourne',
    title: 'Business Development Representative',
    company_name: 'Zendesk',
    company_website: 'https://zendesk.com',
    location: 'Melbourne, Australia',
    work_type: 'Hybrid',
    seniority: 'Entry Level',
    sector: 'SaaS',
    description: 'Open doors at ANZ\'s fastest-growing tech companies for Zendesk\'s customer experience suite. Ideal for a recent graduate or early-career professional with a hunger for tech sales.',
    base_salary: 'A$60k - A$72k',
    ote: 'A$85k - A$105k',
    commission_structure: 'Per SQO and pipeline value created, paid monthly.',
    currency: 'AUD',
    application_url: 'https://zendesk.com/jobs',
    contact_email: 'anz-sdr@zendesk.com',
    featured: 0,
  },
  {
    id: 'sdr-gong-remote',
    title: 'Outbound SDR',
    company_name: 'Gong',
    company_website: 'https://gong.io',
    location: 'Remote (US)',
    work_type: 'Remote',
    seniority: 'Entry Level',
    sector: 'SaaS',
    description: 'Run targeted outbound sequences to VP Sales and RevOps personas. Gong provides world-class call coaching — you will sharpen your skills faster here than anywhere else.',
    base_salary: '$55k - $65k',
    ote: '$85k - $100k',
    commission_structure: 'Monthly commission per SQO. Quarterly kickers.',
    currency: 'USD',
    application_url: 'https://gong.io/careers',
    contact_email: 'sdr@gong.io',
    featured: 0,
  },
  {
    id: 'bdr-workday-sydney',
    title: 'Business Development Representative',
    company_name: 'Workday',
    company_website: 'https://workday.com',
    location: 'Sydney, Australia',
    work_type: 'On-site',
    seniority: 'Entry Level',
    sector: 'SaaS',
    description: 'Identify and qualify enterprise opportunities for Workday\'s HCM and Finance platform across ANZ. Strong BDR program with structured promotion criteria.',
    base_salary: 'A$65k - A$75k',
    ote: 'A$90k - A$110k',
    commission_structure: 'Monthly variable tied to SQO quota and pipeline value.',
    currency: 'AUD',
    application_url: 'https://workday.com/careers',
    contact_email: 'apac-sdr@workday.com',
    featured: 0,
  },
  {
    id: 'sdr-intercom-nyc',
    title: 'Sales Development Representative',
    company_name: 'Intercom',
    company_website: 'https://intercom.com',
    location: 'New York, NY',
    work_type: 'On-site',
    seniority: 'Entry Level',
    sector: 'SaaS',
    description: 'Join a high-energy SDR team in NYC. Generate pipeline for Intercom\'s AI customer service platform through creative outbound to CX, CS, and product leaders.',
    base_salary: '$55k - $68k',
    ote: '$80k - $100k',
    commission_structure: 'Monthly SQO quota. Uncapped. SPIFs for top performers.',
    currency: 'USD',
    application_url: 'https://intercom.com/careers',
    contact_email: 'nyc-sdr@intercom.com',
    featured: 0,
  },
  {
    id: 'bdr-okta-austin',
    title: 'Business Development Representative',
    company_name: 'Okta',
    company_website: 'https://okta.com',
    location: 'Austin, TX',
    work_type: 'Hybrid',
    seniority: 'Entry Level',
    sector: 'Cybersecurity',
    description: 'Open enterprise accounts for Okta\'s identity platform. Work alongside field AEs covering the South-Central territory. Equity included from day one.',
    base_salary: '$50k - $62k',
    ote: '$75k - $95k',
    commission_structure: 'Monthly per SQO. Annual equity refresh.',
    currency: 'USD',
    application_url: 'https://okta.com/company/careers',
    contact_email: 'bdr@okta.com',
    featured: 0,
  },
  {
    id: 'sdr-datadog-paris',
    title: 'Sales Development Representative, France',
    company_name: 'Datadog',
    company_website: 'https://datadoghq.com',
    location: 'Paris, France',
    work_type: 'Hybrid',
    seniority: 'Entry Level',
    sector: 'SaaS',
    description: 'Drive outbound prospecting across French enterprise accounts for Datadog\'s monitoring platform. Fluent French required. Strong ramp support and career progression.',
    base_salary: '€42k - €52k',
    ote: '€65k - €80k',
    commission_structure: 'Monthly SQO quota. Uncapped.',
    currency: 'EUR',
    application_url: 'https://datadoghq.com/careers',
    contact_email: 'france-sdr@datadoghq.com',
    featured: 0,
  },
  {
    id: 'bdr-stripe-singapore',
    title: 'Business Development Representative, APAC',
    company_name: 'Stripe',
    company_website: 'https://stripe.com',
    location: 'Singapore',
    work_type: 'On-site',
    seniority: 'Entry Level',
    sector: 'FinTech',
    description: 'Source and qualify payments and fintech opportunities across Southeast Asia for Stripe\'s enterprise suite. Mandarin or Bahasa language skills highly valued.',
    base_salary: 'S$55k - S$70k',
    ote: 'S$80k - S$100k',
    commission_structure: 'Monthly commissions on qualified opportunities.',
    currency: 'SGD',
    application_url: 'https://stripe.com/jobs',
    contact_email: 'apac-bdr@stripe.com',
    featured: 0,
  },

  // --- Sales Manager (8) ---
  {
    id: 'sm-salesforce-chicago',
    title: 'Sales Manager, Mid-Market',
    company_name: 'Salesforce',
    company_website: 'https://salesforce.com',
    location: 'Chicago, IL',
    work_type: 'Hybrid',
    seniority: 'Senior',
    sector: 'SaaS',
    description: 'Lead a team of 6 mid-market AEs covering the Midwest. Coach reps on Challenger methodology, own forecast calls, and partner with sales engineering on complex deals.',
    base_salary: '$150k - $175k',
    ote: '$280k - $330k',
    commission_structure: 'Team attainment override plus individual management bonus.',
    currency: 'USD',
    application_url: 'https://salesforce.com/careers',
    contact_email: 'managers@salesforce.com',
    featured: 1,
  },
  {
    id: 'sm-hubspot-boston',
    title: 'Sales Manager, SMB',
    company_name: 'HubSpot',
    company_website: 'https://hubspot.com',
    location: 'Boston, MA',
    work_type: 'Hybrid',
    seniority: 'Senior',
    sector: 'SaaS',
    description: 'Manage a team of 8 SMB AEs in HubSpot\'s Boston hub. First-line manager responsible for quota assignment, rep coaching, hiring, and quarterly business reviews.',
    base_salary: '$130k - $155k',
    ote: '$220k - $265k',
    commission_structure: 'Team quota attainment bonus paid quarterly.',
    currency: 'USD',
    application_url: 'https://hubspot.com/careers',
    contact_email: 'manager-hiring@hubspot.com',
    featured: 0,
  },
  {
    id: 'sm-zendesk-sydney',
    title: 'Sales Manager, ANZ',
    company_name: 'Zendesk',
    company_website: 'https://zendesk.com',
    location: 'Sydney, Australia',
    work_type: 'Hybrid',
    seniority: 'Senior',
    sector: 'SaaS',
    description: 'Lead Zendesk\'s ANZ sales team of 5 AEs. Own $6M team quota, run weekly forecasting and pipeline reviews, and drive go-to-market strategy with regional marketing.',
    base_salary: 'A$160k - A$185k',
    ote: 'A$270k - A$320k',
    commission_structure: 'Team attainment override. RSU component included.',
    currency: 'AUD',
    application_url: 'https://zendesk.com/jobs',
    contact_email: 'anz-hiring@zendesk.com',
    featured: 1,
  },
  {
    id: 'sm-okta-london',
    title: 'Sales Manager, UKI',
    company_name: 'Okta',
    company_website: 'https://okta.com',
    location: 'London, UK',
    work_type: 'Hybrid',
    seniority: 'Senior',
    sector: 'Cybersecurity',
    description: 'Manage Okta\'s UKI commercial sales team. Coach reps through identity security deals, own regional forecasting, and work closely with channel and alliance partners.',
    base_salary: '£110k - £130k',
    ote: '£200k - £240k',
    commission_structure: 'Team quota override, paid quarterly with annual true-up.',
    currency: 'GBP',
    application_url: 'https://okta.com/company/careers',
    contact_email: 'uk-leaders@okta.com',
    featured: 0,
  },
  {
    id: 'sm-intercom-remote',
    title: 'Sales Manager, Growth',
    company_name: 'Intercom',
    company_website: 'https://intercom.com',
    location: 'Remote (US)',
    work_type: 'Remote',
    seniority: 'Senior',
    sector: 'SaaS',
    description: 'Manage a distributed team of 6 AEs selling Intercom\'s growth segment. Own team quota of $8M ARR and build an async-first management culture.',
    base_salary: '$140k - $165k',
    ote: '$240k - $290k',
    commission_structure: 'Quarterly attainment bonus plus stock options.',
    currency: 'USD',
    application_url: 'https://intercom.com/careers',
    contact_email: 'sales-leadership@intercom.com',
    featured: 0,
  },
  {
    id: 'sm-snowflake-singapore',
    title: 'Sales Manager, SEA',
    company_name: 'Snowflake',
    company_website: 'https://snowflake.com',
    location: 'Singapore',
    work_type: 'On-site',
    seniority: 'Senior',
    sector: 'SaaS',
    description: 'Lead Snowflake\'s SEA sales team across Singapore, Malaysia, and Indonesia. Own $10M team quota and partner with regional SEs, partners, and professional services.',
    base_salary: 'S$180k - S$210k',
    ote: 'S$300k - S$360k',
    commission_structure: 'Team attainment override. RSU refresh annually.',
    currency: 'SGD',
    application_url: 'https://snowflake.com/careers',
    contact_email: 'sea-leaders@snowflake.com',
    featured: 0,
  },
  {
    id: 'sm-gong-nyc',
    title: 'Sales Manager, Enterprise',
    company_name: 'Gong',
    company_website: 'https://gong.io',
    location: 'New York, NY',
    work_type: 'Hybrid',
    seniority: 'Senior',
    sector: 'SaaS',
    description: 'Manage a team of 5 enterprise AEs selling Gong to large sales organizations. Use Gong itself to coach and develop your team. Own $12M team quota.',
    base_salary: '$155k - $180k',
    ote: '$270k - $325k',
    commission_structure: 'Quarterly override on team attainment plus individual deal bonus.',
    currency: 'USD',
    application_url: 'https://gong.io/careers',
    contact_email: 'em-hiring@gong.io',
    featured: 1,
  },
  {
    id: 'sm-datadog-berlin',
    title: 'Sales Manager, DACH',
    company_name: 'Datadog',
    company_website: 'https://datadoghq.com',
    location: 'Berlin, Germany',
    work_type: 'Hybrid',
    seniority: 'Senior',
    sector: 'SaaS',
    description: 'Lead Datadog\'s DACH sales team. Own forecasting, rep development, and regional GTM for Germany, Austria, and Switzerland. German language strongly preferred.',
    base_salary: '€130k - €155k',
    ote: '€230k - €280k',
    commission_structure: 'Team override. Annual equity refresh.',
    currency: 'EUR',
    application_url: 'https://datadoghq.com/careers',
    contact_email: 'dach-leaders@datadoghq.com',
    featured: 0,
  },

  // --- Account Manager (7) ---
  {
    id: 'am-stripe-london',
    title: 'Strategic Account Manager',
    company_name: 'Stripe',
    company_website: 'https://stripe.com',
    location: 'London, UK',
    work_type: 'Hybrid',
    seniority: 'Senior',
    sector: 'FinTech',
    description: 'Manage and expand relationships with Stripe\'s largest European enterprise accounts. Drive product adoption across the full payments and treasury suite.',
    base_salary: '£100k - £125k',
    ote: '£200k - £250k',
    commission_structure: '10% on net new ARR, expansion bonus at 110% attainment.',
    currency: 'GBP',
    application_url: 'https://stripe.com/jobs',
    contact_email: 'am-emea@stripe.com',
    featured: 0,
  },
  {
    id: 'am-salesforce-sydney',
    title: 'Account Manager, Enterprise',
    company_name: 'Salesforce',
    company_website: 'https://salesforce.com',
    location: 'Sydney, Australia',
    work_type: 'Hybrid',
    seniority: 'Senior',
    sector: 'SaaS',
    description: 'Own renewal and expansion across a portfolio of 20 enterprise accounts in ANZ. Cross-sell Einstein AI features into existing Salesforce deployments.',
    base_salary: 'A$120k - A$145k',
    ote: 'A$220k - A$270k',
    commission_structure: 'Commission on net new ARR and renewal uplift.',
    currency: 'AUD',
    application_url: 'https://salesforce.com/careers',
    contact_email: 'anz-am@salesforce.com',
    featured: 0,
  },
  {
    id: 'am-zendesk-sf',
    title: 'Account Manager, Strategic',
    company_name: 'Zendesk',
    company_website: 'https://zendesk.com',
    location: 'San Francisco, CA',
    work_type: 'Hybrid',
    seniority: 'Senior',
    sector: 'SaaS',
    description: 'Manage a portfolio of Zendesk\'s 50 largest US customers. Drive NRR above 120% through expansion, upsell, and strong executive relationships.',
    base_salary: '$100k - $125k',
    ote: '$190k - $235k',
    commission_structure: 'NRR-based commission plus expansion ARR bonus.',
    currency: 'USD',
    application_url: 'https://zendesk.com/jobs',
    contact_email: 'strat-am@zendesk.com',
    featured: 0,
  },
  {
    id: 'am-hubspot-melbourne',
    title: 'Account Manager, Growth',
    company_name: 'HubSpot',
    company_website: 'https://hubspot.com',
    location: 'Melbourne, Australia',
    work_type: 'Remote',
    seniority: 'Mid-Level',
    sector: 'SaaS',
    description: 'Grow and retain a portfolio of 80 mid-market HubSpot customers in Australia and New Zealand. Own product adoption and identify upsell opportunities across CRM, Marketing Hub, and Service Hub.',
    base_salary: 'A$90k - A$110k',
    ote: 'A$150k - A$185k',
    commission_structure: 'Expansion commission on ARR growth and annual renewal uplift.',
    currency: 'AUD',
    application_url: 'https://hubspot.com/careers',
    contact_email: 'anz-am@hubspot.com',
    featured: 0,
  },
  {
    id: 'am-okta-chicago',
    title: 'Account Manager, Commercial',
    company_name: 'Okta',
    company_website: 'https://okta.com',
    location: 'Chicago, IL',
    work_type: 'On-site',
    seniority: 'Mid-Level',
    sector: 'Cybersecurity',
    description: 'Own the post-sale relationship for a portfolio of 60 commercial Okta customers. Drive product expansion, ensure high NPS, and partner with technical support on escalations.',
    base_salary: '$85k - $105k',
    ote: '$155k - $190k',
    commission_structure: 'Renewal attainment plus upsell commission paid quarterly.',
    currency: 'USD',
    application_url: 'https://okta.com/company/careers',
    contact_email: 'am@okta.com',
    featured: 0,
  },
  {
    id: 'am-gong-remote',
    title: 'Customer Account Manager',
    company_name: 'Gong',
    company_website: 'https://gong.io',
    location: 'Remote (US)',
    work_type: 'Remote',
    seniority: 'Mid-Level',
    sector: 'SaaS',
    description: 'Grow Gong revenue within an existing book of 50 mid-market accounts. Partner with CSMs to drive product adoption and surface upsell opportunities.',
    base_salary: '$90k - $110k',
    ote: '$160k - $200k',
    commission_structure: 'Expansion ARR commission, uncapped.',
    currency: 'USD',
    application_url: 'https://gong.io/careers',
    contact_email: 'am@gong.io',
    featured: 0,
  },
  {
    id: 'am-datadog-nyc',
    title: 'Technical Account Manager',
    company_name: 'Datadog',
    company_website: 'https://datadoghq.com',
    location: 'New York, NY',
    work_type: 'Hybrid',
    seniority: 'Senior',
    sector: 'SaaS',
    description: 'Own technical and commercial relationships across Datadog\'s largest US accounts. Drive product adoption across APM, logs, and security, and identify multi-product expansion.',
    base_salary: '$115k - $140k',
    ote: '$200k - $245k',
    commission_structure: 'Usage growth commission plus net new product commission.',
    currency: 'USD',
    application_url: 'https://datadoghq.com/careers',
    contact_email: 'tam@datadoghq.com',
    featured: 0,
  },

  // --- VP of Sales (5) ---
  {
    id: 'vp-sales-snowflake-remote',
    title: 'VP of Sales, Americas',
    company_name: 'Snowflake',
    company_website: 'https://snowflake.com',
    location: 'Remote (US)',
    work_type: 'Remote',
    seniority: 'VP / Executive',
    sector: 'SaaS',
    description: 'Scale Snowflake\'s Americas commercial business. Own $80M quota, lead 4 regional sales managers, and partner with marketing and alliances to drive pipeline coverage.',
    base_salary: '$220k - $260k',
    ote: '$440k - $520k',
    commission_structure: 'Annual attainment bonus plus significant equity package.',
    currency: 'USD',
    application_url: 'https://snowflake.com/careers',
    contact_email: 'exec-hiring@snowflake.com',
    featured: 1,
  },
  {
    id: 'vp-sales-gong-sf',
    title: 'VP of Sales, EMEA',
    company_name: 'Gong',
    company_website: 'https://gong.io',
    location: 'San Francisco, CA',
    work_type: 'Hybrid',
    seniority: 'VP / Executive',
    sector: 'SaaS',
    description: 'Build and lead Gong\'s EMEA sales organisation from London hub. Hire regional managers, define territory strategy, and own $30M EMEA quota for next fiscal year.',
    base_salary: '$200k - $240k',
    ote: '$400k - $480k',
    commission_structure: 'Regional attainment bonus plus equity.',
    currency: 'USD',
    application_url: 'https://gong.io/careers',
    contact_email: 'exec@gong.io',
    featured: 1,
  },
  {
    id: 'vp-sales-intercom-remote',
    title: 'VP of Sales',
    company_name: 'Intercom',
    company_website: 'https://intercom.com',
    location: 'Remote (US)',
    work_type: 'Remote',
    seniority: 'VP / Executive',
    sector: 'SaaS',
    description: 'Own Intercom\'s global sales organisation. Lead 3 regional VPs across Americas, EMEA, and APAC. Own $120M ARR target and report directly to the Chief Revenue Officer.',
    base_salary: '$240k - $280k',
    ote: '$480k - $560k',
    commission_structure: 'Company-wide ARR attainment bonus plus significant equity.',
    currency: 'USD',
    application_url: 'https://intercom.com/careers',
    contact_email: 'exec@intercom.com',
    featured: 1,
  },
  {
    id: 'vp-sales-okta-london',
    title: 'VP of Sales, EMEA',
    company_name: 'Okta',
    company_website: 'https://okta.com',
    location: 'London, UK',
    work_type: 'Hybrid',
    seniority: 'VP / Executive',
    sector: 'Cybersecurity',
    description: 'Lead Okta\'s EMEA field sales organisation. Manage 5 country managers, own $75M EMEA quota, and define the go-to-market strategy in partnership with channel and MSSP partners.',
    base_salary: '£190k - £225k',
    ote: '£380k - £450k',
    commission_structure: 'Regional quota attainment plus equity RSU refresh.',
    currency: 'GBP',
    application_url: 'https://okta.com/company/careers',
    contact_email: 'emea-exec@okta.com',
    featured: 0,
  },
  {
    id: 'vp-sales-datadog-remote',
    title: 'VP of Sales, Commercial',
    company_name: 'Datadog',
    company_website: 'https://datadoghq.com',
    location: 'Remote (US)',
    work_type: 'Remote',
    seniority: 'VP / Executive',
    sector: 'SaaS',
    description: 'Own Datadog\'s commercial segment globally. Lead 6 sales managers and a team of 40 AEs. Drive $60M new ARR and own commercial segment strategy across cloud, DevOps, and security buyers.',
    base_salary: '$210k - $250k',
    ote: '$420k - $500k',
    commission_structure: 'Annual attainment bonus plus equity.',
    currency: 'USD',
    application_url: 'https://datadoghq.com/careers',
    contact_email: 'vp-sales@datadoghq.com',
    featured: 0,
  },

  // --- Business Development (5) ---
  {
    id: 'bd-stripe-sf',
    title: 'Business Development Manager, Partnerships',
    company_name: 'Stripe',
    company_website: 'https://stripe.com',
    location: 'San Francisco, CA',
    work_type: 'Hybrid',
    seniority: 'Senior',
    sector: 'FinTech',
    description: 'Drive strategic partnerships with platform and marketplace companies for Stripe Connect. Own deal sourcing, negotiation, and post-launch GTM execution.',
    base_salary: '$130k - $155k',
    ote: '$210k - $255k',
    commission_structure: 'Deal-based commission on TPV influenced plus milestone bonuses.',
    currency: 'USD',
    application_url: 'https://stripe.com/jobs',
    contact_email: 'partnerships@stripe.com',
    featured: 0,
  },
  {
    id: 'bd-salesforce-london',
    title: 'Business Development Director, ISV',
    company_name: 'Salesforce',
    company_website: 'https://salesforce.com',
    location: 'London, UK',
    work_type: 'Hybrid',
    seniority: 'Director',
    sector: 'SaaS',
    description: 'Grow Salesforce\'s ISV AppExchange ecosystem across EMEA. Sign new ISV partners, support joint GTM, and drive influenced ARR through partner-sourced opportunities.',
    base_salary: '£110k - £135k',
    ote: '£190k - £235k',
    commission_structure: 'Partner-influenced ARR commission plus new logo bonus.',
    currency: 'GBP',
    application_url: 'https://salesforce.com/careers',
    contact_email: 'isv-emea@salesforce.com',
    featured: 0,
  },
  {
    id: 'bd-snowflake-remote',
    title: 'Business Development Manager, Channels',
    company_name: 'Snowflake',
    company_website: 'https://snowflake.com',
    location: 'Remote (US)',
    work_type: 'Remote',
    seniority: 'Mid-Level',
    sector: 'SaaS',
    description: 'Develop and manage a portfolio of cloud reseller and GSI partners for Snowflake\'s data cloud. Drive partner-sourced pipeline and co-sell execution with field sales teams.',
    base_salary: '$105k - $130k',
    ote: '$180k - $220k',
    commission_structure: 'Partner-sourced deal commission plus quarterly enablement bonus.',
    currency: 'USD',
    application_url: 'https://snowflake.com/careers',
    contact_email: 'channels@snowflake.com',
    featured: 0,
  },
  {
    id: 'bd-hubspot-remote',
    title: 'Business Development Manager, Agency Partners',
    company_name: 'HubSpot',
    company_website: 'https://hubspot.com',
    location: 'Remote (US)',
    work_type: 'Remote',
    seniority: 'Mid-Level',
    sector: 'SaaS',
    description: 'Recruit and grow HubSpot\'s Solutions Partner ecosystem across North America. Train agency partners on HubSpot\'s platform and drive partner-referred revenue growth.',
    base_salary: '$90k - $110k',
    ote: '$155k - $190k',
    commission_structure: 'Partner revenue commission plus tier upgrade bonus.',
    currency: 'USD',
    application_url: 'https://hubspot.com/careers',
    contact_email: 'partner-bd@hubspot.com',
    featured: 0,
  },
  {
    id: 'bd-zendesk-singapore',
    title: 'Business Development Manager, APAC',
    company_name: 'Zendesk',
    company_website: 'https://zendesk.com',
    location: 'Singapore',
    work_type: 'Hybrid',
    seniority: 'Senior',
    sector: 'SaaS',
    description: 'Drive strategic alliances and channel development across SEA, ANZ, and Japan for Zendesk\'s CX platform. Own influenced pipeline targets and partner co-sell execution.',
    base_salary: 'S$110k - S$135k',
    ote: '187k - S$230k',
    commission_structure: 'Partnership deal commission plus milestone bonuses.',
    currency: 'SGD',
    application_url: 'https://zendesk.com/jobs',
    contact_email: 'apac-bd@zendesk.com',
    featured: 0,
  },

  // --- Sales Director (5) ---
  {
    id: 'sd-workday-london',
    title: 'Sales Director, UKI',
    company_name: 'Workday',
    company_website: 'https://workday.com',
    location: 'London, UK',
    work_type: 'Hybrid',
    seniority: 'Director',
    sector: 'SaaS',
    description: 'Lead Workday\'s UKI enterprise sales team of 8 AEs. Own £25M team quota, run quarterly business reviews with C-suite, and drive net-new logo acquisition across FTSE 500 accounts.',
    base_salary: '£160k - £190k',
    ote: '£290k - £350k',
    commission_structure: 'Team attainment override plus individual director bonus.',
    currency: 'GBP',
    application_url: 'https://workday.com/careers',
    contact_email: 'uk-leaders@workday.com',
    featured: 1,
  },
  {
    id: 'sd-servicenow-sf',
    title: 'Director of Sales, West',
    company_name: 'ServiceNow',
    company_website: 'https://servicenow.com',
    location: 'San Francisco, CA',
    work_type: 'Hybrid',
    seniority: 'Director',
    sector: 'SaaS',
    description: 'Lead ServiceNow\'s West region enterprise team. Own $35M team quota across 3 managers and 18 AEs. Report to the VP of Americas and define West region GTM priorities.',
    base_salary: '$175k - $210k',
    ote: '$315k - $380k',
    commission_structure: 'Annual attainment bonus plus equity.',
    currency: 'USD',
    application_url: 'https://servicenow.com/careers',
    contact_email: 'west-director@servicenow.com',
    featured: 0,
  },
  {
    id: 'sd-okta-remote',
    title: 'Sales Director, Federal',
    company_name: 'Okta',
    company_website: 'https://okta.com',
    location: 'Remote (US)',
    work_type: 'Remote',
    seniority: 'Director',
    sector: 'Cybersecurity',
    description: 'Own Okta\'s Federal civilian and defense business. Lead a team of FedRAMP-cleared AEs and channel managers. Security clearance or ability to obtain required.',
    base_salary: '$185k - $220k',
    ote: '$330k - $400k',
    commission_structure: 'Federal quota attainment bonus plus equity.',
    currency: 'USD',
    application_url: 'https://okta.com/company/careers',
    contact_email: 'federal@okta.com',
    featured: 0,
  },
  {
    id: 'sd-datadog-london',
    title: 'Sales Director, Northern Europe',
    company_name: 'Datadog',
    company_website: 'https://datadoghq.com',
    location: 'London, UK',
    work_type: 'Hybrid',
    seniority: 'Director',
    sector: 'SaaS',
    description: 'Lead Datadog\'s Northern Europe team across UK, Nordics, and Benelux. Own £20M team quota, manage 2 country managers and 12 AEs, and drive regional GTM with marketing.',
    base_salary: '£155k - £185k',
    ote: '£280k - £340k',
    commission_structure: 'Regional attainment override. RSU refresh on promotion.',
    currency: 'GBP',
    application_url: 'https://datadoghq.com/careers',
    contact_email: 'northern-eu-director@datadoghq.com',
    featured: 0,
  },
  {
    id: 'sd-snowflake-sydney',
    title: 'Sales Director, ANZ',
    company_name: 'Snowflake',
    company_website: 'https://snowflake.com',
    location: 'Sydney, Australia',
    work_type: 'On-site',
    seniority: 'Director',
    sector: 'SaaS',
    description: 'Own Snowflake\'s ANZ sales organisation. Lead 3 sales managers and 15 AEs across enterprise and commercial segments. Own A$28M team quota and report to the APAC VP.',
    base_salary: 'A$195k - A$230k',
    ote: 'A$340k - A$410k',
    commission_structure: 'Annual attainment override plus equity RSU grant.',
    currency: 'AUD',
    application_url: 'https://snowflake.com/careers',
    contact_email: 'anz-director@snowflake.com',
    featured: 0,
  },
]

export async function seedJobs(pool: mysql.Pool): Promise<{ inserted: number; total: number }> {
  let inserted = 0
  for (const job of jobs) {
    try {
      await pool.execute(
        `INSERT INTO jobs
          (id, title, company_name, company_website, location, work_type, seniority, sector,
           description, base_salary, ote, commission_structure, currency, application_url,
           contact_email, featured, status)
         VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, 'live')
         ON DUPLICATE KEY UPDATE title = VALUES(title)`,
        [
          job.id, job.title, job.company_name, job.company_website, job.location,
          job.work_type, job.seniority, job.sector, job.description, job.base_salary,
          job.ote, job.commission_structure, job.currency, job.application_url,
          job.contact_email, job.featured,
        ]
      )
      inserted++
    } catch (err) {
      console.error(`  seed ERR ${job.id}:`, err)
    }
  }
  return { inserted, total: jobs.length }
}
